Fix posts responsive
AnguHashBlog/angular pull request #84
Opened 2024-03-18 00:18 UTC by hossameldinfahmi

## This PR Closes Issue 
closes #

## Description

## What type of PR is this? (check all applicable)

- [ ] 🅰️ Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [yes ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings
[Attach screenshots or recordings if applicable]
![Screenshot 2024-03-18 021819](https://github.com/AnguHashBlog/angular/assets/117823250/8b3c5ee3-5c29-4c1f-a842-48d441e87b39)

## Steps to QA

## Added to documentation?
- [ ] 📜 README.md
- [yes ] 🙅 no documentation needed

## [Optional] Post-deployment tasks
[Specify any post-deployment tasks that need to be performed]

## [Optional] What gif best describes this PR or how it makes you feel? 
[Embed gif or describe the feeling in plain text]

2024-03-18 08:11 UTC, monacodelisa requested changes

2024-03-18 08:11 UTC, monacodelisa commented on angular-app/src/app/components/posts/posts.component.scss
> +      @media (max-width: 768px) {
@hossameldinfahmi this is a good start, please adjust the placement of the media query - it should be placed below all the other styles.

also - in your screenshot the header and the footer are not present - have you checked to see how they look ? Responsiveness is something that relates to the whole view and before we jump to making adjustments to the inner component, adjustments should be made to the outer components that wrap up the view. 

What you can do is - ither handle header and footer within this issue, or if you really only want to work on the post cards - you can wait until the responsiveness has been applied to the header and the footer. 

Please let me know what you prefer to do and if you need any help, maybe I can assign the header & footer responsiveness to someone and we can help you get to the part that you would like to work on.

2024-03-19 07:52 UTC, hossameldinfahmi commented on angular-app/src/app/components/posts/posts.component.scss
> +      @media (max-width: 768px) {
@monacodelisa Thanks for your notice, that's great i will work on the header and the footer responsive and I will also resolve your comments.

2024-03-19 08:12 UTC, hossameldinfahmi commented
@monacodelisa , I've improved the responsiveness of the header and I moved the relevant styles to the bottom of the SCSS page. The footer's responsiveness is already satisfactory and doesn't require any further modifications.

2024-03-19 08:13 UTC, monacodelisa commented on angular-app/src/app/components/posts/posts.component.scss
> +      @media (max-width: 768px) {
@hossameldinfahmi cool, looks good carry on 👍

2024-03-19 08:14 UTC, monacodelisa commented
> @monacodelisa , I've improved the responsiveness of the header and I moved the relevant styles to the bottom of the SCSS page. The footer's responsiveness is already satisfactory and doesn't require any further modifications.

ok will have a look at your changes

2024-03-19 08:24 UTC, monacodelisa commented on angular-app/src/app/components/header/header.component.scss
>  }
@hossameldinfahmi great job on this it's looking very nice I just had a look, one final thing and I can approve it for merge right after - do you see that there is one `}` left here below ? 

the entire media query 

```
@media (max-width: 767px) {
    .toolbar-row {
      flex-direction: column;
      padding-bottom: 12px;

      .toolbar-row-start,
      .toolbar-row-end {
        width: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        align-items: center;
      }
      .series{
        flex-direction: column;
        align-items: center;
      }
    }
  }
```
needs to go below the last `}` 
there will be more styles probably added in the future and it is a very good start to making the app responsive :)

2024-03-19 09:43 UTC, hossameldinfahmi commented on angular-app/src/app/components/header/header.component.scss
>  }
@monacodelisa Thanks a lot i moved it.

2024-03-19 09:51 UTC, monacodelisa approved these changes

2024-03-19 09:52 UTC, cleancodecraft approved these changes

2024-03-19 09:52 UTC, samplelittlered approved these changes

2024-03-19 09:54 UTC, merged

2024-03-19 09:54 UTC, monacodelisa commented
@hossameldinfahmi thank you :)